config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'homes#top'
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update, :new]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :orders_details, only:[:update]
  end

  namespace :public do
    root 'homes#top'
    get 'about' => 'homes#about'
    resources :items, only:[:index, :show]
    resources :customers, only:[:show, :edit, :update] do
       collection do
          get '/mypage' => 'customers#show'
          get '/confirm' =>  'customers#confirm'
          patch '/withdraw_processing' =>  'customers#withdraw_processing'
        end
    end
    resources :cart_items, only:[:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only:[:index, :show, :new, :create ] do
      collection do
         post '/confirm' =>  'orders#confirm'
         get '/thank_you' =>  'orders#thank_you'
      end
    end
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
  end

  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admins, controllers: {
   sessions: 'admin/sessions'
  }

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

   def subtotal
    item.with_tax_price * amount
   end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cart_items, dependent: :destroy
         has_many :orders,  dependent: :destroy
         has_many :addresses, dependent: :destroy

   # is_deletedがfalseならtrueを返すようにしている
  # def active_for_authentication?
  #   super && (is_active == false)
  # end

end

app/models/genre.rb
class Genre < ApplicationRecord

   has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :order_details
  attachment :image

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  
  def sum_of_order_price
    subtotal + shipping_cost
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

   def subtotal
    item.with_tax_price * amount
   end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customers_path
  end



  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :postal_code, :address, :telephone_number)
  end


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end



  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all
    @amount = 0
    @customers = Customer.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    #byebug
    item.save
    redirect_to admin_items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
   item = Item.find(params[:id])
   item.update(item_params)
   redirect_to admin_items_path
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :is_active, :genre_id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  

  # def reject_cusotmer
  #   @customer = Customer.find_by(name: params[:user][:name])
  #   if @customer
  #     if @customer.valid_password?(params[:user][:password]) && (@customer.delete == false)
  #       flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
  #       redirect_to new_customer_registration_path
  #     else
  #       flash[:notice] = "項目を入力してください"
  #     end
  #   end
  # end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<h2><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</h2>

<%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>

　  <p>名前：
    <div class="field">
    <%= f.label :（性） %>
    <%= f.text_field :first_name, autocomplete: "current-first_name" %>
    </div>

    <div class="field">
    <%= f.label :（名） %>
    <%= f.text_field :last_name, autocomplete: "current-last_name" %>
    </div>
  </p>

  <p>フリガナ：
    <div class="field">
    <%= f.label :（セイ） %>
    <%= f.text_field :first_name_kana, autocomplete: "current-first_name_kana" %>
    </div>
    <div class="field">
    <%= f.label :（メイ） %>
    <%= f.text_field :last_name_kana, autocomplete: "current-last_name_kana" %>
    </div>
  </p>

  <p>
    <div class="field">
    <%= f.label :メールアドレス %><br />
    <%= f.email_field :email, autocomplete: "current-email" %>
    </div>
  </p>

  <p>
    <div class="field">
    <%= f.label :郵便番号（ハイフンなし） %><br />
    <%= f.number_field :postal_code, autocomplete: "current-post_cade" %>
    </div>
  </p>

  <p>
    <div class="field">
    <%= f.label :住所 %><br />
    <%= f.text_field :address, autocomplete: "current-address" %>
    </div>
  </p>

  <p>
    <div class="field">
    <%= f.label :電話番号（ハイフンなし） %><br />
    <%= f.number_field :telephone_number, autocomplete: "current-telphone_number" %>
    </div>
  </p>

  <p>
    <div class="actions">
    <%= f.submit "変更を保存" %>
    </div>
  </p>

 

<% end %>

app/views/admin/customers/index.html.erb
<h1>会員一覧</h1>

<table>
  <thead>
    <th>会員ID</th>
    <th>氏名</th>
    <th>メールアドレス</th>
    <th>ステータス</th>
  </thead>
  <% @customers.each do |customer| %>
  <tbody>
    <td><%= customer.id %></td>
    <td><%= link_to admin_customer_path(customer.id) do %>
        <%= customer.first_name %><%= customer.last_name %>
          <% end %></td>
    <td><%= customer.email %></td>
    <td><% if customer.is_active == true %>
                      有効
        <% else %>
                      退会
        <% end %></td>
  </tbody>
  <% end %>
</table>

app/views/admin/customers/show.html.erb
<h1><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報</h1>

<p>会員ID:<%= @customer.id %></p>
<p>氏名:<%= @customer.first_name %><%= @customer.last_name %></p>
<p>フリガナ:<%= @customer.first_name_kana %><%= @customer.last_name_kana %></p>
<p>郵便番号:<%= @customer.postal_code %></p>
<p>住所:<%= @customer.address %></p>
<p>電話番号:<%= @customer.telephone_number %></p>
<p>メールアドレス:<%= @customer.email %></p>
<p>会員ステータス: <td><% if @customer.is_active == true %>
                             有効
                        <% elsif @customer.is_active == false %>
                             退会
                        <% end %></td>



<p><%= link_to "編集する", edit_admin_customer_path(@customer.id) %></p>

app/views/customers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/customers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>