config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'homes#top'
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update, :new]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :orders_details, only:[:update]
  end

  namespace :public do
    root 'homes#top'
    get 'about' => 'homes#about'
    resources :items, only:[:index, :show]
    resources :customers, only:[:show, :edit, :update] do
       collection do
          get '/mypage' => 'customers#show'
          get '/confirm' =>  'customers#confirm'
          patch '/withdraw_processing' =>  'customers#withdraw_processing'
        end
    end
    resources :cart_items, only:[:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resources :orders, only:[:index, :show, :new, :create ] do
      collection do
         post '/confirm' =>  'orders#confirm'
         get '/thank_you' =>  'orders#thank_you'
      end
    end
    resources :addresses, only:[:index, :create, :edit, :update, :destroy]
  end

  devise_for :customers, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admins, controllers: {
   sessions: 'admin/sessions'
  }

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

   def subtotal
    item.with_tax_price * amount
   end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cart_items, dependent: :destroy
         has_many :orders,  dependent: :destroy
         has_many :addresses, dependent: :destroy

   # is_deletedがfalseならtrueを返すようにしている
  # def active_for_authentication?
  #   super && (is_active == false)
  # end

end

app/models/genre.rb
class Genre < ApplicationRecord

   has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :order_details
  attachment :image

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  
  def sum_of_order_price
    subtotal + shipping_cost
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

   def subtotal
    item.with_tax_price * amount
   end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end



  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all
    @amount = 0
    @customers = Customer.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    #byebug
    item.save
    redirect_to admin_items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
   item = Item.find(params[:id])
   item.update(item_params)
   redirect_to admin_items_path
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :is_active, :genre_id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  

  # def reject_cusotmer
  #   @customer = Customer.find_by(name: params[:user][:name])
  #   if @customer
  #     if @customer.valid_password?(params[:user][:password]) && (@customer.delete == false)
  #       flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
  #       redirect_to new_customer_registration_path
  #     else
  #       flash[:notice] = "項目を入力してください"
  #     end
  #   end
  # end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_details_helper.rb
module Admin::OrdersDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<h1>ジャンル編集</h1>

<%= form_with model: @genre, url:admin_genre_path(@genre.id), method: :patch, local:true do |f| %>

<p>ジャンル名
   <%= f.text_field :name %></p>

<p><%= f.submit "変更を保存" %></p>

<% end %>

app/views/admin/genres/index.html.erb
<h1>ジャンル一覧・追加</h1>

<%= form_with model: @genre, url:admin_genres_path, method: :post, local:true do |f| %>
<p>ジャンル名
<%= f.text_field :name %></p>

<p><%= f.submit "新規登録" %></p>
<% end %>

<table>
  <thead>
    <th>ジャンル</th>
    <th></th>
  </thead>
  <% @genres.each do |genre| %>
  <tbody>
    <td><%= genre.name %></td>
    <td><%= link_to "編集", edit_admin_genre_path(genre.id) %></td>
  </tbody>
  <% end %>
</table>

app/views/admin/items/edit.html.erb
<h1>商品詳細</h1>


<%= form_with model: @item, url:admin_item_path(@item.id), local:true do |f| %>
<p>商品画像：
<%= attachment_image_tag @item, :image, :fil, 40, 50 %>
<labe for="inputImage">ファイルを選択</labe>
<%= f.attachment_field :image, placeholder: "選択されていません" %>
</p>

<p>
商品名：
<%= f.text_field :name %>
</p>

<p>
商品説明：
<%= f.text_area :introduction %>
</p>

<p>
ジャンル：
<%= f.collection_select(:genre_id, Genre.all, :id, :name) %>
</p>

<p>
税込み価格：
<%= f.number_field :price %>円
</p>



<p>
<%= f.submit "変更を保存" %>
</p>
<% end %>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>
<%= link_to "新規登録", new_admin_item_path  %>

<table>
  <thead>
    <th>商品ID</th>
    <th>商品名</th>
    <th>税抜価格</th>
    <th>ジャンル</th>
    <th>ステータス</th>
  </thead>
  <% @items.each do |item| %>
  <tbody>
    <td><%= item.id %></td>


    <td><%= link_to admin_item_path(item.id) do %>
        <%= item.name %>
        <% end %></td>


    <td><%= item.price %></td>
    <td><%= item.genre.name %></td>
    <td></td>
  </tbody>
  <% end %>
</table>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>

<%= form_with model: @item, url:admin_items_path, method: :post, local:true do |f| %>

<p>商品画像：
<%= attachment_image_tag @item, :image, :fil, 100,  100 %>
<labe for="inputImage">ファイルを選択</labe>
<%= f.attachment_field :image, placeholder: "選択されていません" %>
</p>

<p>
商品名：
<%= f.text_field :name %>
</p>

<p>
商品説明：
<%= f.text_area :introduction %>
</p>

<p>
ジャンル：
<%= f.collection_select(:genre_id, Genre.all, :id, :name) %>
</p>

<p>
税込み価格：
<%= f.number_field :price %>円
</p>


<p>
<%= f.submit "新規登録" %>
</p>
<% end %>

app/views/admin/items/show.html.erb
<h1>商品詳細</h1>

<p><%= attachment_image_tag @item, :image, :fill, 100, 100, fallback: "no_image.jpg" %></p>

<p>商品名:
  <%= @item.name %></p>

<p>商品説明:
   <%= @item.introduction %></p>

<p>ジャンル:
   <%= @item.genre.name %></p>

<p>税込価格:
   <%= @item.price %></p>

<p>販売ステータス</p>

<p><%=  link_to "編集", edit_admin_item_path(@item.id)  %></p>

app/views/admin/orders/show.html.erb
<h1>注文履歴詳細</h1>

<table>
  <tr>
    <th>名前</th>
    <td><%= @order.name %></td>
  </tr>
  <tr>
    <th>注文日</th>
    <td><%= @order.created_at.to_s(:datetime_jp) %></td>
  </tr>
  <tr>
    <th>配送先</th>
    <td><%= @order.postal_code %>
        <%= @order.address %>
        <%= @order.name %></td>
  </tr>
  <tr>
    <th>支払方法</th>
    <td><%= @order.payment_method_i18n %></td>
  </tr>
</table>

<p>
<table>
  <thead>
    <th>商品</th>
    <th>単価（税込）</th>
    <th>個数</th>
    <th>小計</th>
  </thead>
    <% @order_details.each do |order_detail| %>
  <tbody>
    <tr>
    <td><%= order_detail.item.name %></td>
    <td><%= order_detail.item.with_tax_price %></td>
    <td><%= order_detail.amount %></td>
    <td><%= order_detail.subtotal %></td>
    </tr>
  </tbody>
   <% end %>
</table>
</p>

<p>
  <table>
  <tr>
    <th>商品合計</th>
    <td><%= @order.order_details.sum(&:subtotal) %></td>
  </tr>
  <tr>
    <th>配送料</th>
    <td><%= @order.shipping_cost %></td>
  </tr>
  <tr>
    <th>ご請求額</th>
    <td><%= @order.total_payment %></td>
  </tr>
</table>
</p>